/**
 * /health/ready must SAY whether photo identification is on — and must not
 * refuse to be ready because it isn't.
 *
 * Why this exists: vision going off is silent by construction. `config.js`
 * treats ANTHROPIC_API_KEY as an optional feature var, so its absence is a
 * `console.warn` at boot and nothing else; `vision.http.js` then answers
 * `200 {available: false, suggestion: null}`, which is a *successful*
 * response. The capture flow simply stops offering names. Nothing errors,
 * nothing alerts, and the only way to tell from outside was to notice the
 * feature had quietly stopped working.
 *
 * That is exactly what happened on 2026-08-30: the key was never declared in
 * `pw.json`, so it was never in the Vault bundle the deploy writes `.env`
 * from, and a container recreation left it absent. Diagnosis needed the
 * orchestrator's own logs. It should have needed one unauthenticated curl.
 *
 * These are source-level assertions rather than a live request: the handler
 * is inline in `server/index.js`, which boots the whole app and needs a
 * database and object storage to answer at all. The two properties worth
 * pinning are both visible in the source, and both are things a later edit
 * could plausibly get wrong.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const INDEX = fs.readFileSync(path.join(__dirname, '..', 'index.js'), 'utf8');

/** The body of the /health/ready handler, from its route to the closing `});`. */
function readyHandler() {
  const start = INDEX.indexOf("app.get('/health/ready'");
  assert.notEqual(start, -1, "/health/ready is no longer registered in index.js");
  const end = INDEX.indexOf('\n});', start);
  assert.notEqual(end, -1, 'could not find the end of the /health/ready handler');
  return INDEX.slice(start, end);
}

test('/health/ready reports whether vision and match are enabled', () => {
  const handler = readyHandler();
  assert.match(handler, /vision:\s*config\.vision\.enabled\s*\?/,
    '/health/ready must report vision state — an absent ANTHROPIC_API_KEY is '
    + 'otherwise invisible from outside the box');
  assert.match(handler, /match:\s*config\.match\.enabled\s*\?/,
    '/health/ready must report match state for the same reason');
});

test('readiness does NOT depend on vision — a missing key must not fail the deploy gate', () => {
  const handler = readyHandler();
  const readyLine = handler.split('\n').find((l) => /const ready\s*=/.test(l));
  assert.ok(readyLine, 'could not find the `ready` computation');

  // The PW deploy gate points at this endpoint (see the comment above it), so
  // anything folded into `ready` can fail a deploy. Vision is optional by
  // design — absent on a fresh install and in local dev — so gating on it
  // would break deploys for every install without a key.
  assert.doesNotMatch(readyLine, /vision|match/,
    '`ready` must not depend on vision or match: they are optional features, '
    + 'and the PW deploy gate reads this endpoint');
});

test('/health/ready never exposes the API key itself', () => {
  // Comments stripped first: the handler's own comment names the env var to
  // explain why the state is reported, and matching that would be matching
  // prose. What must not appear is a *reference* — code that could put the
  // value, its length, or its prefix into an unauthenticated response.
  const code = readyHandler().replace(/\/\/.*$/gm, '');
  assert.doesNotMatch(code, /apiKey|process\.env\.ANTHROPIC_API_KEY/,
    '/health/ready is unauthenticated — report the derived state, never the key');
});

test('ANTHROPIC_API_KEY is declared in pw.json so the deploy reproduces it', () => {
  const pw = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'pw.json'), 'utf8'));
  const external = pw.external_secrets || [];
  const internal = pw.secrets || [];

  assert.ok(external.includes('ANTHROPIC_API_KEY'),
    'ANTHROPIC_API_KEY must be declared in pw.json external_secrets. The deploy '
    + 'regenerates .env from the Vault bundle on every run, so an undeclared key '
    + 'is one a container recreation silently drops.');

  // `secrets` are auto-generated by the orchestrator and are fail-closed at
  // deploy time; `external_secrets` are operator-filled and deliberately are
  // not. Putting an operator-supplied key in `secrets` would both have the
  // orchestrator generate a random value over it and fail every deploy until
  // it was populated. The two lists must stay disjoint.
  assert.ok(!internal.includes('ANTHROPIC_API_KEY'),
    'ANTHROPIC_API_KEY must NOT be in pw.json secrets — that list is auto-generated '
    + 'and fail-closed; an operator-provided key belongs in external_secrets');
});
