/**
 * DO THE PRINTED SYMBOLS ACTUALLY DECODE? (#109)
 *
 * `labels.geometry.test.js` proves the rasterised label is geometrically exact:
 * every QR module matches `QRCode.create(url).modules` bit for bit, the Code 128
 * is exactly 3 dots per module, and since #326 the symbols land on the printer's
 * dot grid. That is a guarantee about GEOMETRY, and it is the stronger one — a
 * decoder's error correction hides wrong modules that a bit-for-bit comparison
 * catches. But it is not a guarantee about DECODABILITY, and the two can come
 * apart in both directions:
 *
 *   - a QR whose quiet zone is too tight for a real detector's finder-pattern
 *     search is bit-perfect and unreadable;
 *   - a Code 128 with the wrong check digit is bit-perfect against its own
 *     encoder's module list and rejected by every scanner on earth.
 *
 * So this file does the thing the geometry suite deliberately does not: it hands
 * the rasterised bitmap to a REAL DECODER and asserts the payload round-trips.
 *
 * WHICH DECODER, AND WHY THIS ONE. The client scans with `html5-qrcode`, which
 * vendors ZXing (`html5-qrcode/esm/third_party/zxing-js.umd`) and maps its own
 * format enum straight onto `ZXing.BarcodeFormat`. `@zxing/library` is that same
 * decoder, headless — the closest thing to the phone that can run in CI. It is a
 * devDependency; CI's `npm audit --production` does not see it, and it pulls in
 * exactly one transitive package.
 *
 * CLOSING THE LOOP TO THE APP. Decoding to the right string is only half the
 * claim. What matters is: printed symbol -> decoder -> `extractTlyCode` -> the
 * right entity. `extractTlyCode` is client TypeScript, so the payloads decoded
 * here are written to a committed fixture and `client/src/lib/tly.printed-
 * labels.test.ts` runs them through the REAL shipping function. Re-implementing
 * that regex on this side would prove nothing about what the scanner does.
 *
 * The fixture is written across the tree, into client/src/lib/__fixtures__/,
 * because that is where it is READ and the client's tsconfig only sees `src`.
 * Producer here, consumer there, one committed file between them.
 *
 * WHAT THIS STILL DOES NOT PROVE. It reads the bitmap the printer is handed, not
 * ink on paper. Thermal bleed, media and darkness settings sit downstream, and
 * only a physical scan-back (the operator half of #109) can speak to those.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const QRCode = require('qrcode');
const ZXing = require('@zxing/library');
const code128 = require('../src/modules/labels/code128');

const {
  Labels, CLIENT_URL, DPI, SKIP, renderOnePage, dots,
  findBarcodeInRow, SMALL, MEDIUM, MANIFEST,
} = require('./helpers/label-raster');

// The fixture the client test reads. Regenerated by this file on every run and
// compared against what is committed, so a stale one fails the server suite
// rather than quietly letting the client assert against yesterday's payloads.
const FIXTURE = path.join(
  __dirname, '..', '..', 'client', 'src', 'lib', '__fixtures__', 'printed-label-decodes.json',
);
const DECODER = '@zxing/library';

// ── the decoder ────────────────────────────────────────────────────────────

/**
 * Wrap one of our greyscale rasters as something ZXing will read.
 *
 * `decodePng` already hands back one luminance byte per pixel, which is exactly
 * what RGBLuminanceSource wants when the buffer length matches w*h. HybridBinarizer
 * is the binarizer html5-qrcode uses, so the thresholding path is the app's too
 * rather than a friendlier one chosen to make this pass.
 */
function bitmapOf(img) {
  const source = new ZXing.RGBLuminanceSource(new Uint8ClampedArray(img.data), img.w, img.h);
  return new ZXing.BinaryBitmap(new ZXing.HybridBinarizer(source));
}

function hints(formats) {
  const h = new Map();
  h.set(ZXing.DecodeHintType.TRY_HARDER, true);
  if (formats) h.set(ZXing.DecodeHintType.POSSIBLE_FORMATS, formats);
  return h;
}

/** Decode the QR on a page raster. Throws NotFoundException if there isn't one. */
function decodeQr(img) {
  return new ZXing.QRCodeReader().decode(bitmapOf(img), hints()).getText();
}

/** Decode a Code 128 on a page raster. Throws NotFoundException if there isn't one. */
function decodeCode128(img) {
  const h = hints([ZXing.BarcodeFormat.CODE_128]);
  return new ZXing.MultiFormatOneDReader(h).decode(bitmapOf(img), h).getText();
}

/**
 * "The decoder refused to read this", in all the forms ZXing spells it: no
 * symbol located (NotFound), located but the error correction could not recover
 * it (Checksum), or recovered into something that is not a valid symbol
 * (Format). Matched by type rather than by message because ZXing throws these
 * with an undefined message, so a regex on the text matches nothing useful.
 */
const isDecodeFailure = (err) => err instanceof ZXing.NotFoundException
  || err instanceof ZXing.ChecksumException
  || err instanceof ZXing.FormatException;

// ── damage, for the negative controls ──────────────────────────────────────

/** A copy of the raster with a rectangle painted white. */
function erase(img, x0, y0, x1, y1) {
  const out = { w: img.w, h: img.h, data: Buffer.from(img.data) };
  for (let y = Math.max(0, y0); y < Math.min(img.h, y1); y++) {
    for (let x = Math.max(0, x0); x < Math.min(img.w, x1); x++) out.data[y * img.w + x] = 255;
  }
  return out;
}

/** A copy of the raster with a rectangle painted black. */
function ink(img, x0, y0, x1, y1) {
  const out = { w: img.w, h: img.h, data: Buffer.from(img.data) };
  for (let y = Math.max(0, y0); y < Math.min(img.h, y1); y++) {
    for (let x = Math.max(0, x0); x < Math.min(img.w, x1); x++) out.data[y * img.w + x] = 0;
  }
  return out;
}

/**
 * Locate the Code 128 in a page raster: which rows it spans, where its first
 * element starts, and how wide a module is.
 *
 * Self-locating via the geometry rig's own row matcher, so it needs no layout
 * constants — the same reason that helper works the way it does.
 */
function locateBarcode(img, modules) {
  const rows = [];
  let anchor = null;
  for (let y = 0; y < img.h; y++) {
    const hit = findBarcodeInRow(img, y, modules);
    if (!hit) continue;
    rows.push(y);
    if (!anchor) anchor = hit;
  }
  assert.ok(anchor, 'no raster row matches the canonical Code 128 element widths');
  let x = 0;
  for (let i = 0; i < anchor.first; i++) x += anchor.runs[i].len;
  return { x, scale: anchor.scale, y0: rows[0], y1: rows[rows.length - 1] + 1 };
}

// ── render + decode everything once ────────────────────────────────────────

let cached = null;

/**
 * Every symbol tally prints, rasterised at 203 dpi and read back.
 *
 * Memoised because both the assertions and the fixture want the same numbers,
 * and rasterising the same three PDFs four times over is pure waste.
 */
async function decoded() {
  if (cached) return cached;

  const smallPdf = await Labels.renderLabelPdf([SMALL], 'small');
  const mediumPdf = await Labels.renderLabelPdf([MEDIUM], 'medium');
  const largePdf = await Labels.renderManifestPdf(MANIFEST, 'large');

  const small = await renderOnePage(smallPdf, 'small');
  const medium = await renderOnePage(mediumPdf, 'medium');
  const large = await renderOnePage(largePdf, 'large');

  cached = {
    small: { ...small, entity: SMALL, code: SMALL.qrCode },
    medium: { ...medium, entity: MEDIUM, code: MEDIUM.qrCode },
    large: { ...large, entity: MANIFEST.header, code: MANIFEST.header.qrCode },
  };
  return cached;
}

/** Every (preset, format) pair the printer produces, and what it decoded to. */
async function decodedSymbols() {
  const pages = await decoded();
  const out = [];
  for (const preset of ['small', 'medium', 'large']) {
    out.push({
      preset,
      format: 'QR_CODE',
      code: pages[preset].code,
      decoded: decodeQr(pages[preset].img),
    });
  }
  out.push({
    preset: 'large',
    format: 'CODE_128',
    code: pages.large.code,
    decoded: decodeCode128(pages.large.img),
  });
  return out;
}

// ── the claims ─────────────────────────────────────────────────────────────

for (const [preset, entity, kind] of [
  ['small', SMALL, '2x1 item tag'],
  ['medium', MEDIUM, '3x3 bin tag'],
]) {
  test(`${preset} (${kind}): a real decoder reads the printed QR back as the deep link`, { skip: SKIP }, async () => {
    const pages = await decoded();
    const text = decodeQr(pages[preset].img);
    // Exact equality, deliberately. "It decodes to something" would pass on a
    // label carrying the wrong entity's code, which is the failure that
    // actually costs someone an afternoon in a garage.
    assert.equal(text, `${CLIENT_URL}/s/${entity.qrCode}`,
      `${preset}: the printed QR decodes to ${JSON.stringify(text)}`);
  });
}

test('large (4x6 manifest): a real decoder reads the printed QR back as the deep link', { skip: SKIP }, async () => {
  const pages = await decoded();
  const text = decodeQr(pages.large.img);
  assert.equal(text, `${CLIENT_URL}/s/${MANIFEST.header.qrCode}`,
    `large: the manifest header QR decodes to ${JSON.stringify(text)}`);
});

test('large (4x6 manifest): a real decoder reads the printed Code 128 back as the bare code', { skip: SKIP }, async () => {
  const pages = await decoded();
  const text = decodeCode128(pages.large.img);
  // The barcode carries the bare TLY code, not the URL — that is what a laser
  // scanner at a desk types into the code field. Exact equality also means the
  // Code 128 CHECK DIGIT is right: ZXing rejects the symbol outright if it is
  // not, and no amount of correct module geometry would tell us that.
  assert.equal(text, MANIFEST.header.qrCode,
    `large: the printed Code 128 decodes to ${JSON.stringify(text)}`);
});

test('the 2x1 and 3x3 tags carry no barcode — nothing there decodes as Code 128', { skip: SKIP }, async () => {
  // The rasterised counterpart of the source-level pin in the geometry suite.
  // If a Code 128 is ever added to a thermal tag, this fails and whoever added
  // it has to extend the decode coverage rather than ship an unread symbol.
  const pages = await decoded();
  for (const preset of ['small', 'medium']) {
    assert.throws(() => decodeCode128(pages[preset].img), isDecodeFailure,
      `${preset}: something on this label decodes as a Code 128, but only the manifest is supposed to carry one`);
  }
});

test('the decode has teeth: a QR missing a finder pattern does not read', { skip: SKIP }, async () => {
  // NEGATIVE CONTROL. A decode assertion that has never been seen to fail is
  // not evidence — TRY_HARDER plus Reed-Solomon makes ZXing forgiving, so this
  // pins that it is not forgiving enough to pass on a symbol that is not there.
  const pages = await decoded();
  const { img, placement } = pages.small;
  const slots = QRCode.create(`${CLIENT_URL}/s/${SMALL.qrCode}`).modules.size + 2;
  const perModule = Math.round(dots(placement.wPt)) / slots;
  const left = Math.floor(dots(placement.xPt));
  const top = Math.floor(dots(placement.yPt));

  // The top-left finder pattern plus its quiet zone and separator: 9 module
  // slots square from the image origin. Take that away and the detector has
  // nothing to lock onto.
  const damaged = erase(img, left, top, left + Math.ceil(9 * perModule), top + Math.ceil(9 * perModule));
  assert.throws(() => decodeQr(damaged), isDecodeFailure,
    'a QR with a finder pattern erased still decoded — the decode assertions above prove nothing');
});

test('the decode has teeth: a Code 128 with one element widened does not read', { skip: SKIP }, async () => {
  // NEGATIVE CONTROL for the barcode, and the sharper of the two: the symbol is
  // still entirely present and still looks like a barcode. Only the widths are
  // wrong, which is exactly the class of defect the geometry suite measures and
  // a decoder is supposed to reject rather than error-correct through.
  const pages = await decoded();
  const { modules } = code128.encode(MANIFEST.header.qrCode);
  const band = locateBarcode(pages.large.img, modules);

  // Ink over the first space (element 1), merging it into the bars either side.
  const spaceStart = band.x + modules[0] * band.scale;
  const damaged = ink(pages.large.img, spaceStart, band.y0, spaceStart + modules[1] * band.scale, band.y1);
  assert.throws(() => decodeCode128(damaged), isDecodeFailure,
    'a Code 128 with a deformed element still decoded — the decode assertion above proves nothing');
});

test('every decoded payload is written to the fixture the client test reads', { skip: SKIP }, async () => {
  const symbols = await decodedSymbols();
  const fresh = {
    _comment: 'GENERATED by server/test/labels.decode.test.js — do not hand-edit. '
      + 'These are the payloads a real decoder read back off the rasterised label PDFs at '
      + `${DPI} dpi. client/src/lib/tly.printed-labels.test.ts runs them through the real `
      + 'extractTlyCode, which is the half of the round trip that cannot run in node.',
    clientUrl: CLIENT_URL,
    dpi: DPI,
    decoder: DECODER,
    symbols,
  };

  const before = fs.existsSync(FIXTURE) ? fs.readFileSync(FIXTURE, 'utf8') : null;
  const after = `${JSON.stringify(fresh, null, 2)}\n`;
  fs.mkdirSync(path.dirname(FIXTURE), { recursive: true });
  fs.writeFileSync(FIXTURE, after);

  // The file has just been rewritten, so the fix for a failure here is simply
  // to commit it. Asserting AFTER writing is what makes a stale fixture a red
  // CI run instead of a client test quietly agreeing with itself.
  assert.equal(before, after,
    'client/src/lib/__fixtures__/printed-label-decodes.json was stale or missing. It has been '
    + 'regenerated from this run — commit it. The client test asserts against the committed '
    + 'copy, so an uncommitted one means the client is checking yesterday\'s payloads.');
});
